#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/professor-rhymes/Documents/installations/MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: cs36300_spring2017_algebraic_v2

depend: cs36300_spring2017_algebraic_v2-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.cs36300_spring2017_algebraic_v2 $(@)

.PHONY: cs36300_spring2017_algebraic_v2
cs36300_spring2017_algebraic_v2:
	@$(MAKE) -f Makefile.cs36300_spring2017_algebraic_v2 all

.PHONY: cs36300_spring2017_algebraic_v2-depend
cs36300_spring2017_algebraic_v2-depend:
	@$(MAKE) -f Makefile.cs36300_spring2017_algebraic_v2 depend

project_name_list:
	@echo cs36300_spring2017_algebraic_v2
